# Generated by Django 4.2 on 2023-04-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smb_base', '0004_alter_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
