# Generated by Django 4.2 on 2023-04-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smb_base', '0007_remove_comment_likes_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
