# Generated by Django 4.2 on 2023-04-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smb_base', '0008_delete_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
