# Generated by Django 4.2 on 2023-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smb_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
